# Generated by Django 3.2.3 on 2021-06-21 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ISBN', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de libro')),
                ('nombreLibro', models.CharField(max_length=50, verbose_name='Nombre de libro')),
                ('autor', models.CharField(max_length=50, verbose_name='Nombre del autor')),
                ('Descripcion', models.CharField(max_length=100, verbose_name='Descripcion del libro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
